apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-etcd-pv
spec:
  capacity: { storage: 10Gi }
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/data/milvus-etcd", type: DirectoryOrCreate }
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [k8s-node3]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-minio-pv
spec:
  capacity: { storage: 20Gi }
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/data/milvus-minio", type: DirectoryOrCreate }
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [k8s-node3]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-standalone-pv
spec:
  capacity: { storage: 50Gi }
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/data/milvus-standalone", type: DirectoryOrCreate }
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [k8s-node3]
